### ISSUE TITLE
How to use custom icons

### ISSUE THREAD

**Issue by TahaMalas** [devefy/Flutter-Story-App-UI#1]
How are you adding the custom icons to your flutter app and does it lose its dimensions on big screen sizes?

**Comment by juwencheng** [comment]
you could check the official document , here it is https://flutter.dev/docs/development/ui/assets-and-images

**Comment by kharisazhar** [comment]
to use custom icons, you should convert .png/jpg image into .svg then .svg to .ttf 
convert .svg to .ttf using https://icomoon.io/app/#/select/font
see detail https://www.youtube.com/watch?v=uojqV6hUEDc,
dimensions depend on your original icon because the custom icon will convert from .svg to .ttf

**Comment by TahaMalas** [comment]
Thanks it worked perfectly!

**Comment by TahaMalas** [comment]
Thanks it worked perfectly!
