### ISSUE TITLE
ERROR: Lost connection to device

### ISSUE THREAD

**Issue by Jagrit29** [devefy/Flutter-Story-App-UI#8]
When I am trying to run the app, I am facing this error:-

E/flutter (14833): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (14833): 
F/flutter (14833): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
**Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:64104/CtAje0I7eNo=/**

I have tried it both for Android SDK 29 and 28. Downgrading sdk is not helping.

**Comment by christippett** [comment]
@Jagrit29 I encountered the same issue. Renaming the space in the filename for `Calibre Semibold.otf` and updating its path in `pubspec.yaml` resolved it for me.

**Comment by Jagrit29** [comment]
@christippett, it also worked for me.
Thank you very much.
